services:
  client:
    image: onthesafari/cardamom-client
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
    # don't copy the node_modules to prevent the volume hosted on windows from overwriting the linux packages on the container
      - ./client/src:/usr/src/cardamom/src
    depends_on:
      - nginx
  server:
    image: onthesafari/cardamom-server
    env_file:
      - ${ENV_FILE:-.env.dev}
    # environment:
    #   - FLASK_ENV=${FLASK_ENV}
    build:
      context: ./server
    ports:
      - "8888:5000"
    volumes:
      - ./server:/usr/src/cardamom
    depends_on:
      - database
      - redis
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
  redis:
    image: redis
    ports:
      - "6379:6379"
  database:
    image: "postgres"
    env_file:
      - ${ENV_FILE:-.env.dev}
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
volumes:
  database:
    driver: local
