services:
  client:
    image: onthesafari/cardamom-client
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
    # don't copy the node_modules to prevent the volume hosted on windows from overwriting the linux packages on the container
      - ./client/src:/usr/src/cardamom/src
  server:
    image: onthesafari/cardamom-server
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_PORT=5432
    build:
      context: ./server
    ports:
      - "8888:5000"
    volumes:
      - ./server:/usr/src/cardamom
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
  redis:
    image: redis
    ports:
      - "6379:6379"
  database:
    image: "postgres"
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
volumes:
  database:
    driver: local
